### ISSUE TITLE
Use doctrine/phpcr-odm, doctrine/orm as type names?

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/resource-bundle#24]
As with Sylius prefix with the vendor then the repository type preceded by a slash: `doctrine/phpcr-odm`, `puli/filesystem`

**Comment by ElectricMaxxx** [comment]
does that match for the url usage?

**Comment by wouterj** [comment]
The type names aren't used in the URL, the repository names are used in the URL.

**Comment by dantleech** [comment]
This was about locating the configuration files iirc and clearly delimiting the vendor.
