### ISSUE TITLE
 basepath or base_path also basedir

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/resource-bundle#8]
The CMF currnetly uses `basepath` to indicate paths in the CR repository. It would follow then that we use `basedir` to indicate filesystem paths. But I generally think we should always use underscores - `base_path` and `base_dir`.

**Comment by dantleech** [comment]
PHPCR uses `basedir` instead of `basepath`. We should change all of them to be `base_path`.

**Comment by ElectricMaxxx** [comment]
Is this one still relevant?

**Comment by wouterj** [comment]
Decided to skip this one. Yes, it is a bit inconsistent, but I like `base_dir` way more than `basedir` and renaming `basepath` doesn't seem very usefull to me.
